# name: Mirror Scrapers to Standalone Repositories

# on:
#   push:
#     branches:
#       - main

# jobs:
#   mirror:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.12"

#       - name: Run Mirror Script
#         env:
#           MIRROR_PAT: ${{ secrets.MIRROR_PAT }}
#         run: |
#           python scripts/mirror.py --owner ${{ github.repository_owner }}
